### ISSUE TITLE
`group.strata` argument in `make.ds.analysis`

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsims#12]
Documentation is not clear about utility of this argument, no example available.

> Dataframe with two columns ("design.id" and "analysis.id"). The former gives the strata names as defined in the design (i.e. the region object) the second specifies how they should be grouped (into less strata) for the analyses

- defined in [DS.Analysis.R](https://github.com/DistanceDevelopment/dsims/blob/8a1daef3dfafb122ee7da3a635fb2f5ffeeac66c/R/DS.Analysis.R#L27)
  - but not passed to `ds`

**Comment by LHMarshall** [comment]
I will leave this open as I want to write it into a vignette. I think it needs more explanation in an example than can be given in the R help files. I have however expanded the help so it is clearer as to it's use which I think satisfies this for the 0.2.0 release.
![Screenshot 2021-08-25 at 13 34 56](https://user-images.githubusercontent.com/1295691/130791173-fcaad04d-2a36-4c51-a1b6-288a8d76300e.png)
