### ISSUE TITLE
'make.design' help available from 'dsims'?

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsims#19]
Because users need to know the specification of `make.design` for `dsims` to work, they would need to know to look in the `dssd` package help to find information about that function.  Is there a way to direct the user to that help, or duplicate that help in `dsims`?

**Comment by LHMarshall** [comment]
The following is in version 0.1.1 which is currently on CRAN:

There are links to make.design and make.region (both in dssd) in the make.simulation help under 'See Also'
There are also links to the help files for make.region and make.design in the package description of dsims.
