### ISSUE TITLE
Segmented Grid having issues on a windows machine

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/dsims#35]
This design, which includes both a segmented grid design and a systematic line design, is working correctly on a mac but generates an incorrect set of transects on a windows machine.

**Survey generated on a windows machine:**

![windows_bug](https://user-images.githubusercontent.com/1295691/131923462-19348bf5-be83-474a-a2d3-1020cae89eeb.jpeg)

**Survey generated on a mac:**

![mac_fine](https://user-images.githubusercontent.com/1295691/131923651-641036a0-e472-45b6-96b7-2af96256251e.jpeg)

**Code to reproduce:**

```
  # Set up region
  s1p1 = matrix(c(0,0,0,1.75,2,1.75,2,0,0,0),ncol=2, byrow=TRUE)
  s1p2 = matrix(c(1,2,1,2.5,3.8,2.5,3.8,2,1,2),ncol=2, byrow=TRUE)
  s2p1 = matrix(c(2,0,2,0.5,4,0.5,4,0,2,0),ncol=2, byrow=TRUE)
  s3p1 = matrix(c(4,0,4,2,5,2,5,0,4,0),ncol=2, byrow=TRUE)
  mpol1 = sf::st_multipolygon(list(sf::st_polygon(list(s1p1)),
                                  sf::st_polygon(list(s1p2))))
  mpol2 = sf::st_multipolygon(list(sf::st_polygon(list(s2p1))))
  mpol3 = sf::st_multipolygon(list(sf::st_polygon(list(s3p1))))
  sfc <- sf::st_sfc(mpol1,mpol2,mpol3)
  strata.names <- c("low", "high", "med")
  mp1 <- sf::st_sf(strata = strata.names, geom = sfc)

  region <- make.region(region.name = "main",
                        strata.name = strata.names,
                        shape = mp1)

  # design
  design <- make.design(region = region,
                        transect.type = "line",
                        design = c("segmentedgrid","systematic","systematic"),
                        spacing = c(0.3,0.2,0.2),
                        design.angle = c(90,0,90),
                        seg.length = c(0.1, NA, NA),
                        seg.threshold = 0.5,
                        truncation = 0.1)
  
  transects <- generate.transects(design, region)
  plot(region, transects)
```

**Comment by LHMarshall** [comment]
There is differing behaviour from sf::st_intersection on a mac and on a windows machine. I have reported this as an issue in the sf repository [here](https://github.com/r-spatial/sf/issues/1781)

**Comment by LHMarshall** [comment]
@erex @lenthomas you both have windows machines... can you run the following code and post the resulting plot please? If it tells you there are no samplers let me know that but re-run it a few times as there should be some samplers eventually... but not nearly as many as there should be! This strangely seems to be a windows specific issue, all works fine on mac and ubuntu.

```
library(dssd)  
region <- make.region()
design <- make.design(region = region, 
                      transect.type = "line",
                      design = "segmentedgrid",
                      spacing = 100, 
                      seg.length = 50,
                      seg.threshold = 0,
                      edge.protocol = "minus",
                      truncation = 50)
transects <- generate.transects(design)
plot(region, transects, lwd = 0.8, col = "blue")
```

**Comment by erex** [comment]
Ran the snippet 25 times, about half the time code issued the warning "No transects generated in stratum 1", remaining times when no warning was issued, the resulting plots were degenerate, as this:
![image](https://user-images.githubusercontent.com/330744/132084822-9739bef9-f5e9-4edf-baa5-0a7b562560db.png)

**Comment by LHMarshall** [comment]
@erex thanks! The sf::st_intersection function performs as expected on mac and ubuntu machines but is being weird on windows! I just wanted to know if it was on all windows machines or if it was a coincidence. Any chance you could also run the following code please and paste in the output. Thanks!

```
packageVersion("sf")
sf::sf_extSoftVersion()
```

**Comment by erex** [comment]
```
> packageVersion("sf")
[1] ‘1.0.2’
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.9.0"        "3.2.1"        "7.2.1"         "true" 
    USE_PROJ_H           PROJ 
        "true"        "7.2.1" 
```

**Comment by LHMarshall** [comment]
Ok so I've traced this issue back to the package update to sf-0.9.8.

The segmented grid design still works under the following versions so the current recommended temporary fix (this is only an issue on windows machines) is to roll back the sf version which should install the associated GEOS, GDAL, proj.4 versions as specified below:

```
> packageVersion("sf")
[1] ‘0.9.6’
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true"

> packageVersion("sf")
[1] ‘0.9.7’
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true" 
```

To install either of these versions you will need Rtools installed then you will have to download the .tar.gz file from [here](https://cran.r-project.org/src/contrib/Archive/sf/). Next choose to install from a local directory and point to the downloaded file. It does take a little time to install.

**Comment by erex** [comment]
Should this be a `dssd` issue rather than a `dsims` issue?

**Comment by LHMarshall** [comment]
@erex yup, I just popped a report in over there too. From the looks of the bug thread on sf I think this issue should be resolved soon if it's not already. Sounds like rgdal has been updated to use GEOS 3.9.1 and when the windows binaries on CRAN are rebuilt (they might have been already but I've not had time to check / test things out) then GEOS 3.9.1 should be installed when sf is installed.

**Comment by LHMarshall** [comment]
This issue has now been resolved. You will need to reinstall the sf R library from CRAN. Then if you run the code 
```
sf::sf_extSoftVersion()
```
you should see that the GEOS version has been updated to 3.9.1
