### ISSUE TITLE
`dsims` doesn't trap some types of failures

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsims#70]
Reported by a user on [20Sep22](https://groups.google.com/g/distance-sampling/c/GfUue2U4Be8) that `dsims` fails with following message

```
optimx.check(par, optcfg$ufn, optcfg$ugr, optcfg$uhess, lower, :
Infeasible point, no further tests
```

I presume it is `mrds`, called by `ds` that calls `optimx.check()`.

I'm not sure if [`DS.analysis.R`](https://github.com/DistanceDevelopment/dsims/blob/c2059c3893bba4a7aa07c2e2595ec6e53efe05e9/R/DS.Analysis.R#L235) handles this situation properly, because I'm not sure the event would be classified as either an error or a warning.

Might be indicative of additional problems arising in `mrds` because [optimx.check](https://rdrr.io/cran/optimx/src/R/optimx.check.R) gets to this part of the code only if the parameter estimates have landed outside the bounds for that parameter.  Not sure how that comes to pass.

**Comment by LHMarshall** [comment]
Re-run this simulation and got the following errors:

```
Summary of warnings and errors:
simpleWarning in optimx.check(par, optcfg$ufn, optcfg$ugr, optcfg$uhess, lower, : Parameters or bounds appear to have different scalings.
  This can cause poor performance in optimization. 
  It is important for derivative free methods like BOBYQA, UOBYQA, NEWUOA.
 (Model number: 2) (occurred 2 time(s) in repetition(s):  76, 401)
simpleWarning in ddf.ds(model = dsmodel, data, meta.data = meta.data, control = control, : First partial hessian is singular; using second-partial hessian

 (Model number: 2) (occurred 1 time(s) in repetition(s):  127)
-----
```

Next run produced:
```
> simulacion.paralela.3km <- run.simulation(simulacion.paralela.3km)
Summary of warnings and errors:
simpleWarning in optimx.check(par, optcfg$ufn, optcfg$ugr, optcfg$uhess, lower, : Parameters or bounds appear to have different scalings.
  This can cause poor performance in optimization. 
  It is important for derivative free methods like BOBYQA, UOBYQA, NEWUOA.
 (Model number: 2) (occurred 2 time(s) in repetition(s):  655, 686)
simpleWarning in ddf.ds(model = dsmodel, data, meta.data = meta.data, control = control, : First partial hessian is singular; using second-partial hessian

 (Model number: 2) (occurred 1 time(s) in repetition(s):  767)
-----
```

**Comment by LHMarshall** [comment]
Still cannot replicate so closing
