### ISSUE TITLE
dsims currently not on CRAN

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/dsims#79]
The `dsims` package is currently only available via GitHub, due to an issue with the `dssd` package, on which `dsims` relies.  We're working to resolve this, but in the meantime instructions for installing `dsims` are on the [dsims GitHub home page](https://github.com/DistanceDevelopment/dsims/)

**Comment by erex** [comment]
Regarding CRAN being unavailable as @LHMarshall indicated during DistDev on 24Nov23:

> The CRAN Admin Team will perform system upgrades during the period
> Wednesday November 15 until Thursday November 16, 2023. There will
> be intermittent outages in service during this time.

**Comment by LHMarshall** [comment]
@erex yup the website basically went offline for 2 days. When it was up and running again I got dssd submitted. I couldn't see any current issues talked about however. Two failed submissions and not heard back from my E-mail to CRAN either.

**Comment by LHMarshall** [comment]
Back on CRAN
